version: '3.7'

services:
  flower:
    build: .
    networks:
      local:
        aliases:
          - flower.local
    environment:
      ETCD_HOST: 'etcd.local'
      FLOWER_USERNAME: 'root'
      FLOWER_PASSWORD: 'changeit'
      AMQP_HOST: 'rabbitmq.local'
      AMQP_PORT: 5672
      AMQP_USERNAME: 'user'
      AMQP_PASSWORD: 'password'
      AMQP_ADMIN_HOST: 'rabbitmq.local'
      AMQP_ADMIN_PORT: 15672
      AMQP_ADMIN_USERNAME: 'user'
      AMQP_ADMIN_PASSWORD: 'password'
    ports:
      - '5555:5555'
    depends_on:
      - etcd
      - rabbitmq
    restart: always
    volumes:
      - '.:/opt/celery-flower'

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      local:
        aliases:
          - rabbitmq.local

  etcd:
    image: 'quay.io/coreos/etcd'
    environment:
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd.local:2379,http://etcd.local:4001
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd.local:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd.local:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      local:
        aliases:
          - etcd.local
    volumes:
      - /usr/share/ca-certificates:/etc/ssl/certs

networks:
  local:
    driver: 'bridge'
